jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - continue-on-error: true
      name: Setup Java 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      run: mvn install
    - continue-on-error: true
      run: npm install
    - continue-on-error: true
      run: npm run docs:tsdocs
    - continue-on-error: true
      run: npm run docs:build
    - continue-on-error: true
      name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: docs/.vuepress/dist
name: es4x website
on:
  repository_dispatch:
    types: trigger-ga___gh-pages.yml
