jobs:
  build:
    name: ${{ matrix.version }} on ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      id: cache-java
      name: Cache JVM
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-java-${{ hashFiles('**/pom.xml') }}
        path: '${{ runner.temp }}/java_package.tar.gz

          ~/.m2/repository

          '
        restore-keys: '${{ runner.os }}-java-

          '
    - continue-on-error: true
      name: Setup GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        components: js
        java-version: '17'
        version: ${{ matrix.version }}
    - continue-on-error: true
      name: Run tests
      run: ./mvnw clean verify
    strategy:
      matrix:
        os:
        - ubuntu-latest
        version:
        - dev
name: GraalVM CI (dev)
on:
  repository_dispatch:
    types: trigger-ga___graalvm-dev.yml
